### ISSUE TITLE
기존 구현체 조사 

### ISSUE THREAD

**Issue by lette1394** [oop-training/simple-http-client#4]
1. Java 9, Java 11 - HttpClient
2. Spring RestTemplate (above Spring 5, WebClient)
3. Apache Http Client
4. Unirest
5. OkHttp

**Comment by lette1394** [comment]
curl의 구현을 많이 참고하면 좋을 듯 하다. (~~cpp 읽기너무힘들다~~)

**Comment by lette1394** [comment]
Spring은 내부에서 대부분의 구현체를 지원한다. 
- Netty4
- OkHttp3
- HttpComponents (Apache)
- HttpURLConnection (java)
- intercept (spring)

Unirest는 Apache 모듈을 사용한다 (HttpComponents)

**Comment by LOG-INFO** [comment]
+ Retrofit2 (OkHttp의 Wrapper라는데 좀 더 조사중)
안드할 땐 이거 많이 썼음
