### ISSUE TITLE
아키텍처 논의

### ISSUE THREAD

**Issue by lette1394** [oop-training/simple-http-client#8]
### Motivation
높은 협업도와 모듈화를 달성하기 위함

### 제안
핵심 공통 기능 => `core` (socket, bytebuffer, file IO, plugins, stream, ...)
스펙 종속적 기능 => `h1`, `h2`, ....

h3 까지 생각했을 때, tcp connection이 아닐 수 있다.

### 논의
별도의 repository로 분리할 필요까진 없을까?
ex) `simple-http-client-core`
ex) `simple-http-client-h1-specs`
...

**Comment by LOG-INFO** [comment]
plugins 라면 JSON parser같은걸 말하는건가

**Comment by lette1394** [comment]
추가할 수 있는 확장기능들을 다 plugin 으로 표현하고 있는데, 논의가 필요해보임

**Comment by lette1394** [comment]
## 계층구조 제안
- user interface layer 
- http layer (parser per version, dto, obj mapper, ...)
- core layer (network, io, security)

### user interface layer 
이 라이브러리를 사용하는 user에게 노출되는 interface
자세한 내용은 논의 후 결정
- static vs instance
- config 객체 넘기는 법
- 병렬 실행?
- sync, async 구분?

### http layer 
HTTP 스펙 구현에 대한 layer, 각 HTTP버전 별 하위 모듈로 나뉠 수 있다. 
- parser (h1/h2 header parser, json body parser, multipart parser, ...)
- dto (HttpResponse, Headers, Requests...) 
- support charset, encoding, ...
- security (tls)

### core layer
network와 file io 등에 대해 공통된 로직을 가지는 layer
network, io, common

지원해야 하는 기능들
- sync/async io operation (file, channel, inputStream, bytes, ...)
- support module(plugin) interface - like Junit5's `@ExtendWith` (hook methods), Junit4's `@Rule`
- manage resources (configurable, network connection, closable, ...)
- callback, pipeline, ...

**Comment by lette1394** [comment]
Apache httpcomponent 사용
